[theme]

# Primary accent color for interactive elements.
primaryColor = "#FF6900"

# Background color for the main content area.
backgroundColor = "#101820"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#101820"

# Color used for almost all text.
textColor = "#8ab7e9"
